services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  api:
    build: .
    environment:
      - MONGO_URI=mongodb://mongo:27017/ocr_ingestion
      - JWT_SECRET=dev-secret-key
      - NODE_ENV=production
    ports:
      - "3031:3031"
    depends_on:
      - mongo
volumes:
  mongo_data: {}


